/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tngarsel' at '28/06/16 19:36' with Gradle 2.14
 *
 * @author tngarsel, @date 28/06/16 19:36
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
